# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestseleniumsecond():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_testseleniumsecond(self):
    self.driver.get("https://ceshiren.com/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".d-button-label").click()
    self.driver.find_element(By.ID, "reply-title").send_keys("dddddd")
    self.driver.find_element(By.ID, "ember195").click()
    self.driver.find_element(By.ID, "ember195").send_keys("aaaaaaaaaaaaaaaaaa")
    self.driver.find_element(By.ID, "reply-title").click()
    self.driver.find_element(By.ID, "reply-title").send_keys("test_selenium")
    self.driver.find_element(By.LINK_TEXT, "取消").click()
    element = self.driver.find_element(By.LINK_TEXT, "取消")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "是").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) img").click()
    self.vars["win5625"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win5625"])
  
